### PR TITLE
ci: update vcpkg version

### PR DESCRIPTION
**Pull request by coryan**

### CODE REVIEW

**Comment by dbolduc** [comment]
@coryan - I don't think I ever managed to test this, but this is what the bigtable update could/should look like: https://github.com/GoogleCloudPlatform/functions-framework-cpp/pull/359/commits/1aac2324ca868aa0543be08375d25dd3f023732f

**Comment by dbolduc** [comment]
> this is what the bigtable update could/should look like

I didn't see your commit (https://github.com/GoogleCloudPlatform/functions-framework-cpp/pull/375/commits/b486b762cf0e0abcaa314637c1e22d657ebc9256) when I added my comment. I can make the changes I want in a follow up PR after vcpkg is updated.

**Comment by coryan** [comment]
I will be making more changes to the spanner, bigtable, and Pub/Sub examples to use more modern initialization (e.g. `google::cloud::Options` instead of `*ClientOptions`, and cache the connection but not the resource name).

**Comment by coryan** [comment]
Ugh.  I need to update the buildpack to get a newer vcpkg with a newer `google-cloud-cpp`.   Which is not fun because that change won't be atomic... and the deprecation warnings break the build...  Need to think.  And I need to make the minimal changes first anyway.

**Pull request closed without merging**
